"""
Theme constants for NULL-CODE-ANALYZER
Pure black/white minimalist aesthetic
"""

# Color palette
BG_BLACK = "#000000"
TEXT_WHITE = "#FFFFFF"
TEXT_GRAY = "#4D4D4D"

# Rich color names (for use with rich library)
THEME_COLORS = {
    "primary": "white",
    "secondary": "bright_black",
    "background": "black",
    "error": "white",
    "warning": "white",
    "success": "white",
    "info": "bright_black",
}

# Box drawing characters
BOX_HORIZONTAL = "─"
BOX_VERTICAL = "│"
BOX_TOP_LEFT = "┌"
BOX_TOP_RIGHT = "┐"
BOX_BOTTOM_LEFT = "└"
BOX_BOTTOM_RIGHT = "┘"
BOX_T_DOWN = "┬"
BOX_T_UP = "┴"
BOX_T_RIGHT = "├"
BOX_T_LEFT = "┤"
BOX_CROSS = "┼"

# Animation characters
WAVE_CHARS = ["░", "▒", "▓", "█", "▓", "▒", "░"]
PULSE_CHARS = ["█", "▒"]
BLOCK_CHARS = ["░", "▒", "▓", "█"]

# Logo ASCII art
LOGO = """
███╗   ██╗██╗   ██╗██╗     ██╗         ██████╗ ██████╗ ██████╗ ███████╗
████╗  ██║██║   ██║██║     ██║        ██╔════╝██╔═══██╗██╔══██╗██╔════╝
██╔██╗ ██║██║   ██║██║     ██║        ██║     ██║   ██║██║  ██║█████╗  
██║╚██╗██║██║   ██║██║     ██║        ██║     ██║   ██║██║  ██║██╔══╝  
██║ ╚████║╚██████╔╝███████╗███████╗   ╚██████╗╚██████╔╝██████╔╝███████╗
╚═╝  ╚═══╝ ╚═════╝ ╚══════╝╚══════╝    ╚═════╝ ╚═════╝ ╚═════╝ ╚══════╝
"""

# Ethical disclaimer text with IT Act 2000 specifics
ETHICS_DISCLAIMER = """
┌───────────────────────────────────────────────────────────────────────────┐
│                                                                           │
│  ⚠️  NULL-CODE-ANALYZER ETHICAL USAGE AGREEMENT                           │
│                                                                           │
│  LEGAL NOTICE UNDER INFORMATION TECHNOLOGY ACT, 2000 (INDIA)             │
│                                                                           │
│  Section 43: Unauthorized access penalties up to ₹1 crore                │
│  Section 66: Imprisonment up to 3 years + fines for unauthorized access  │
│                                                                           │
│  You MUST have EXPLICIT WRITTEN PERMISSION to scan code/systems not      │
│  owned by you. This tool is for DEFENSIVE SECURITY TESTING ONLY.         │
│                                                                           │
│  By proceeding, you legally affirm:                                      │
│  • You have authorization for this security test                         │
│  • You will use findings for defensive purposes only                     │
│  • You will follow responsible disclosure practices                      │
│  • You understand criminal penalties for misuse                          │
│                                                                           │
│  To accept these terms, use flag:                                        │
│  --i-accept-ethics                                                       │
│                                                                           │
│  Press Ctrl+C to exit if you do not accept.                              │
│                                                                           │
└───────────────────────────────────────────────────────────────────────────┘
"""

# Report footer
REPORT_FOOTER = "Generated by Null-Code-Analyzer for authorized security testing only - Compliant with IT Act 2000 (India)"
