"""
HTML dashboard export for vulnerability reports
"""

from typing import List
from datetime import datetime
from ..core import VulnerabilityMatch, ScanResult


class HTMLExporter:
    """Export scan results to HTML dashboard"""

    def export(self, scan_result: ScanResult, output_path: str) -> None:
        """
        Export scan results to HTML dashboard
        
        Args:
            scan_result: Complete scan result
            output_path: Output file path
        """
        html = self._build_html(scan_result)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)

    def _build_html(self, scan_result: ScanResult) -> str:
        """Build complete HTML document"""
        vulns_by_severity = self._group_by_severity(scan_result.vulnerabilities)
        
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Null-Code-Analyzer Report</title>
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>NULL-CODE-ANALYZER</h1>
            <p class="subtitle">Security Vulnerability Report</p>
        </header>

        <section class="summary">
            <h2>Scan Summary</h2>
            <div class="stats-grid">
                <div class="stat-box">
                    <div class="stat-value">{len(scan_result.vulnerabilities)}</div>
                    <div class="stat-label">Total Vulnerabilities</div>
                </div>
                <div class="stat-box">
                    <div class="stat-value">{scan_result.scanned_files}</div>
                    <div class="stat-label">Files Scanned</div>
                </div>
                <div class="stat-box">
                    <div class="stat-value">{scan_result.scan_mode.upper()}</div>
                    <div class="stat-label">Scan Mode</div>
                </div>
                <div class="stat-box">
                    <div class="stat-value">{scan_result.duration:.1f}s</div>
                    <div class="stat-label">Duration</div>
                </div>
            </div>
        </section>

        <section class="severity-breakdown">
            <h2>Severity Breakdown</h2>
            <div class="severity-stats">
                <div class="severity-item critical">
                    <span class="severity-label">CRITICAL</span>
                    <span class="severity-count">{len(vulns_by_severity.get('critical', []))}</span>
                </div>
                <div class="severity-item high">
                    <span class="severity-label">HIGH</span>
                    <span class="severity-count">{len(vulns_by_severity.get('high', []))}</span>
                </div>
                <div class="severity-item medium">
                    <span class="severity-label">MEDIUM</span>
                    <span class="severity-count">{len(vulns_by_severity.get('medium', []))}</span>
                </div>
                <div class="severity-item low">
                    <span class="severity-label">LOW</span>
                    <span class="severity-count">{len(vulns_by_severity.get('low', []))}</span>
                </div>
            </div>
        </section>

        <section class="vulnerabilities">
            <h2>Vulnerabilities</h2>
            {self._build_vulnerability_list(scan_result.vulnerabilities)}
        </section>

        <footer>
            <p>Generated by Null-Code-Analyzer on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC</p>
            <p class="legal">For authorized security testing only</p>
        </footer>
    </div>
</body>
</html>"""

    def _get_css(self) -> str:
        """Return CSS styles (black/white theme)"""
        return """
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Courier New', monospace;
            background-color: #000;
            color: #fff;
            padding: 20px;
        }
        .container { max-width: 1200px; margin: 0 auto; }
        header {
            text-align: center;
            padding: 40px 0;
            border-bottom: 2px solid #4D4D4D;
            margin-bottom: 40px;
        }
        h1 { font-size: 48px; letter-spacing: 4px; }
        .subtitle { color: #4D4D4D; margin-top: 10px; }
        h2 {
            font-size: 24px;
            margin-bottom: 20px;
            border-bottom: 1px solid #4D4D4D;
            padding-bottom: 10px;
        }
        .summary { margin-bottom: 40px; }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-top: 20px;
        }
        .stat-box {
            border: 1px solid #4D4D4D;
            padding: 20px;
            text-align: center;
        }
        .stat-value {
            font-size: 36px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .stat-label { color: #4D4D4D; }
        .severity-breakdown { margin-bottom: 40px; }
        .severity-stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 10px;
        }
        .severity-item {
            border: 1px solid #4D4D4D;
            padding: 15px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .severity-label { font-weight: bold; }
        .severity-count { font-size: 24px; }
        .vuln-card {
            border: 1px solid #4D4D4D;
            padding: 20px;
            margin-bottom: 20px;
        }
        .vuln-header {
            display: flex;
            justify-content: space-between;
            margin-bottom: 15px;
        }
        .vuln-type { font-size: 18px; font-weight: bold; }
        .vuln-severity {
            padding: 5px 10px;
            border: 1px solid #fff;
            font-size: 12px;
        }
        .vuln-details { color: #4D4D4D; margin-bottom: 10px; }
        .vuln-code {
            background-color: #1a1a1a;
            padding: 10px;
            border-left: 3px solid #4D4D4D;
            font-family: monospace;
            overflow-x: auto;
        }
        footer {
            text-align: center;
            padding-top: 40px;
            margin-top: 40px;
            border-top: 2px solid #4D4D4D;
            color: #4D4D4D;
        }
        .legal { margin-top: 10px; font-size: 12px; }
        """

    def _build_vulnerability_list(self, vulnerabilities: List[VulnerabilityMatch]) -> str:
        """Build HTML for vulnerability list"""
        if not vulnerabilities:
            return "<p>No vulnerabilities found.</p>"

        html_parts = []
        for vuln in vulnerabilities:
            html_parts.append(f"""
            <div class="vuln-card">
                <div class="vuln-header">
                    <span class="vuln-type">{vuln.type}</span>
                    <span class="vuln-severity">{vuln.severity.upper()}</span>
                </div>
                <div class="vuln-details">
                    <strong>{vuln.cwe_id}</strong> • Line {vuln.line_number} • 
                    Confidence: {vuln.confidence}%
                </div>
                <p>{vuln.description}</p>
                <pre class="vuln-code">{self._escape_html(vuln.code_snippet)}</pre>
            </div>
            """)

        return "".join(html_parts)

    def _group_by_severity(self, vulnerabilities: List[VulnerabilityMatch]) -> dict:
        """Group vulnerabilities by severity"""
        groups = {"critical": [], "high": [], "medium": [], "low": []}
        for vuln in vulnerabilities:
            groups[vuln.severity].append(vuln)
        return groups

    def _escape_html(self, text: str) -> str:
        """Escape HTML special characters"""
        return (text
                .replace('&', '&amp;')
                .replace('<', '&lt;')
                .replace('>', '&gt;')
                .replace('"', '&quot;')
                .replace("'", '&#39;'))
