"""
JSON export for vulnerability reports
"""

import json
from typing import List
from datetime import datetime
from dataclasses import asdict
from ..core import VulnerabilityMatch, ScanResult


class JSONExporter:
    """Export scan results to JSON format"""

    def export(self, scan_result: ScanResult, output_path: str) -> None:
        """
        Export scan results to JSON
        
        Args:
            scan_result: Complete scan result
            output_path: Output file path
        """
        report = self._build_report(scan_result)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=2)

    def _build_report(self, scan_result: ScanResult) -> dict:
        """Build JSON report structure"""
        return {
            "scan_info": {
                "timestamp": datetime.utcnow().isoformat() + "Z",
                "tool": "Null-Code-Analyzer",
                "version": "1.0.0",
                "mode": scan_result.scan_mode,
                "duration_seconds": round(scan_result.duration, 2)
            },
            "summary": {
                "total_files": scan_result.total_files,
                "scanned_files": scan_result.scanned_files,
                "total_vulnerabilities": len(scan_result.vulnerabilities),
                "by_severity": self._count_by_severity(scan_result.vulnerabilities),
                "skipped_files": len(scan_result.skipped_files)
            },
            "vulnerabilities": [
                self._vuln_to_dict(v) for v in scan_result.vulnerabilities
            ],
            "skipped_files": scan_result.skipped_files,
            "legal_notice": "Generated by Null-Code-Analyzer for authorized security testing only"
        }

    def _vuln_to_dict(self, vuln: VulnerabilityMatch) -> dict:
        """Convert vulnerability to dict"""
        return {
            "type": vuln.type,
            "cwe_id": vuln.cwe_id,
            "severity": vuln.severity,
            "confidence": vuln.confidence,
            "line_number": vuln.line_number,
            "code_snippet": vuln.code_snippet,
            "description": vuln.description
        }

    def _count_by_severity(self, vulnerabilities: List[VulnerabilityMatch]) -> dict:
        """Count vulnerabilities by severity"""
        counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}
        for vuln in vulnerabilities:
            counts[vuln.severity] += 1
        return counts
